### ISSUE TITLE
[vortex] TypeError: Cyclic __proto__ value (line:87) - error on start

### ISSUE THREAD

**Issue by dceejay** [PrismTech/node-red-contrib-vortex#1]
Hi,

using latest node.js v6.10.1  (and Node-RED 0.16.2) - I get the above error when trying to start

    [vortex] TypeError: Cyclic __proto__ value (line:87)

I think it's caused by the  previous line (86  -  util.inherits... ), and indeed line 31 - Not sure why you need to extend the event emitter as each node is already an event emitter so should be ok without needing to do that... or am I missing something ?

**Comment by tobymcclean** [comment]
I believe that has been fixed by the latest code in the repository. I have pushed a new version with these changes to the npm registry. Version 0.3.0.

**Comment by dceejay** [comment]
Thanks
